### ISSUE TITLE
IP Address on Auto Configure screen

### ISSUE THREAD

**Issue by bphilli7** [bretep/webcast-auto-conf#1]
The IP Address on my Auto Configure webpage is reporting the default IP address, rather than the DHCP address my JTECH box got.

**Comment by bretep** [comment]
Interesting. The IP address can come from two different API calls. I'm using the API call for the status page which should show static or DHCP. 

J-Tech has the source code for the API so I'll ask them what one I should hit. 

I'll get it resolved soon. :) Thank you for the issue!
